services:
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile.backend.prod
    image: backend:1337
    container_name: backend-prod
    networks:
      - transcendence-net
    expose:
      - "3000"
    volumes:
      - ./app/static:/app/static
      - ./db:/data
  prometheus:
    image: prom/prometheus:v3.7.3
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - transcendence-net
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    depends_on:
      - backend

  frontend:
    build:
      context: ./Front-end
      dockerfile: Dockerfile.frontend.prod
    image: frontend:1337
    container_name: frontend-prod
    ports:
      - "8080:80"
    networks:
      - transcendence-net
    depends_on:
      - backend

networks:
  transcendence-net:
    name: transcendence-net
    driver: bridge

volumes:
  prometheus-data:
    driver: local