services:
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile.backend.prod
    image: backend:1337
    container_name: backend-prod
    networks:
      - transcendence-net
    expose:
      - "3000"
    volumes:
      - ./app/static:/app/static
      - ./db:data

  frontend:
    build:
      context: ./Front-end
      dockerfile: Dockerfile.frontend.prod
    image: frontend:1337
    container_name: frontend-prod
    ports:
      - "8080:80"
    networks:
      - transcendence-net
    depends_on:
      - backend

networks:
  transcendence-net:
    name: transcendence-net
    driver: bridge