services:
  frontend-prod:
    build:
      context: ./Front-end
      dockerfile: Dockerfile.frontend.prod
    image: frontend-prod:1337
    container_name: frontend-prod
    ports:
      - "8443:8443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./Security/ModSecurity/frontend_logs.conf:/etc/nginx/conf.d/00_logging.conf:ro
      - pong-dist:/app/assets/game:ro
    environment:
      - SERVICE_EXT=-prod
    networks:
      - transcendence-prod-net
    depends_on:
      - modSecurity-prod

  auth-service-prod:
    build:
      context: ./app/auth
      dockerfile: ../Dockerfile.microservices.prod
      args:
        - PORT=3001
    image: auth-service-prod:1337
    container_name: auth-service-prod
    environment:
      - VAULT_ADDR=${VAULT_ADDR_PROD}
      - VAULT_SECRET_PATH=${AUTH_SECRET_PATH}
      - AUTH_SERVICE_TOKEN=${AUTH_SERVICE_TOKEN}
      - DATABASE_PATH=/data/auth.db
      - HOST=0.0.0.0
      - DOMAIN=${AUTH_DOMAIN_PROD}
      - SERVICE_EXT=-prod
      - LOG_LEVEL=debug
    expose:
      - 3001
    user: root
    volumes:
      - ./db/auth:/data
      - ./app/static:/app/static
    networks:
      - transcendence-prod-net
    depends_on:
      vault-init-prod:
        condition: service_completed_successfully

  user-service-prod:
    build:
      context: ./app/user-service
      dockerfile: ../Dockerfile.microservices.prod
      args:
        - PORT=3002
    image: user-service-prod:1337
    container_name: user-service-prod
    environment:
      - VAULT_ADDR=${VAULT_ADDR_PROD}
      - VAULT_SECRET_PATH=${USER_SECRET_PATH}
      - USER_SERVICE_TOKEN=${USER_SERVICE_TOKEN}
      - DATABASE_PATH=/data/users.db
      - HOST=0.0.0.0
      - SERVICE_EXT=-prod
      - LOG_LEVEL=debug
    expose:
      - 3002
    user: root
    volumes:
      - ./db/users:/data
      - ./app/static:/app/static
    networks:
      - transcendence-prod-net
    depends_on:
      vault-init-prod:
        condition: service_completed_successfully

  global-chat-prod:
    build:
      context: ./app/chat/global
      dockerfile: ../../Dockerfile.microservices.prod
      args:
        - PORT=3003
    image: global-chat-prod:1337
    container_name: global-chat-prod
    environment:
      - VAULT_ADDR=${VAULT_ADDR_PROD}
      - VAULT_SECRET_PATH=${GLOBAL_CHAT_SECRET_PATH}
      - GLOBAL_CHAT_SERVICE_TOKEN=${GLOBAL_CHAT_SERVICE_TOKEN}
      - DATABASE_PATH=/data/global.db
      - HOST=0.0.0.0
      - SERVICE_EXT=-prod
      - LOG_LEVEL=debug
    expose:
      - 3003
    user: root
    volumes:
      - ./db/chat:/data
    networks:
      - transcendence-prod-net
    depends_on:
      vault-init-prod:
        condition: service_completed_successfully

  private-chat-prod:
    build:
      context: ./app/chat/private
      dockerfile: ../../Dockerfile.microservices.prod
      args:
        - PORT=3004
    image: private-chat-prod:1337
    container_name: private-chat-prod
    environment:
      - VAULT_ADDR=${VAULT_ADDR_PROD}
      - VAULT_SECRET_PATH=${PRIVATE_CHAT_SECRET_PATH}
      - PRIVATE_CHAT_SERVICE_TOKEN=${PRIVATE_CHAT_SERVICE_TOKEN}
      - DATABASE_PATH=/data/private.db
      - HOST=0.0.0.0
      - SERVICE_EXT=-prod
      - LOG_LEVEL=debug
    expose:
      - 3004
    user: root
    volumes:
      - ./db/chat:/data
    networks:
      - transcendence-prod-net
    depends_on:
      vault-init-prod:
        condition: service_completed_successfully

  pong-game-prod:
    build:
      context: ./Pong
      dockerfile: Dockerfile.pong.prod
      args:
        - PORT=3005
    image: pong-game-prod:1337
    container_name: pong-game-prod
    environment:
      - VAULT_ADDR=${VAULT_ADDR_PROD}
      - VAULT_SECRET_PATH=${PONG_SECRET_PATH}
      - PONG_SERVICE_TOKEN=${PONG_SERVICE_TOKEN}
      - HOST=0.0.0.0
      - SERVICE_EXT=-prod
      - LOG_LEVEL=debug
    expose:
      - 3005
    volumes:
      - pong-dist:/pong-dist
    networks:
      - transcendence-prod-net
    depends_on:
      vault-init-prod:
        condition: service_completed_successfully

  vault-prod:
    image: hashicorp/vault:1.21.1
    container_name: vault-prod
    networks:
      - transcendence-prod-net
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_TOKEN}
      - VAULT_ADDR=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK

  vault-init-prod:
    image: hashicorp/vault:1.21.1
    container_name: vault-init-prod
    networks:
      - transcendence-prod-net
    volumes:
      - ./Security/HashicorpVault/hashicorpVault.init.sh:/init.sh
    environment:
      - VAULT_ADDR=${VAULT_ADDR_PROD}
      - VAULT_TOKEN=${VAULT_TOKEN}
      - JWT_SECRET_VALUE=${JWT_SECRET_VALUE}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - INTRA_CLIENT_ID=${INTRA_CLIENT_ID}
      - INTRA_CLIENT_SECRET=${INTRA_CLIENT_SECRET}
      - AUTH_SERVICE_TOKEN=${AUTH_SERVICE_TOKEN}
      - USER_SERVICE_TOKEN=${USER_SERVICE_TOKEN}
      - GLOBAL_CHAT_SERVICE_TOKEN=${GLOBAL_CHAT_SERVICE_TOKEN}
      - PRIVATE_CHAT_SERVICE_TOKEN=${PRIVATE_CHAT_SERVICE_TOKEN}
      - PONG_SERVICE_TOKEN=${PONG_SERVICE_TOKEN}
    entrypoint: /init.sh
    depends_on:
      - vault-prod

  modSecurity-prod:
    image: owasp/modsecurity-crs:4.21.0-nginx-alpine-202512071012
    container_name: modSecurity-prod
    networks:
      - transcendence-prod-net
    environment:
      - MODSEC_RULE_ENGINE=on
      - BLOCKING_PARANOIA=2
    volumes:
      - ./Security/ModSecurity/Nginx.conf:/etc/nginx/templates/conf.d/default.conf.template:ro
      - ./Security/ModSecurity/rules/exceptions.conf:/etc/modsecurity.d/owasp-crs/rules/REQUEST-900-CUSTOM-EXCLUSIONS.conf:ro
      - ./Security/ModSecurity/scan_php.sh:/usr/local/bin/scan_php.sh:ro
      - ./Security/ModSecurity/gateway_logs.conf:/etc/nginx/conf.d/00_logging.conf:ro
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - auth-service-prod
      - user-service-prod
      - global-chat-prod
      - private-chat-prod
      - pong-game-prod

  prometheus-prod:
    image: prom/prometheus:v3.8.1
    container_name: prometheus-prod
    ports:
      - "9090:9090"
    networks:
      - transcendence-prod-net
    volumes:
      - ./Metrics/prometheus/prometheus.prod.yaml:/etc/prometheus/prometheus.yml:ro
      - ./Metrics/prometheus/alertRules.yaml:/etc/prometheus/alertRules.yaml:ro
      - prometheus-data:/prometheus
    depends_on:
      - auth-service-prod
      - user-service-prod
      - global-chat-prod
      - private-chat-prod
      - pong-game-prod

  grafana-prod:
    image: grafana/grafana:12.3.0
    container_name: grafana-prod
    ports:
      - "3000:3000"
    networks:
      - transcendence-prod-net
    volumes:
      - grafana-data:/var/lib/grafana
      - ./Metrics/grafana/provisioning:/etc/grafana/provisioning
      - ./Metrics/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - prometheus-prod

networks:
  transcendence-prod-net:
    name: transcendence-prod-net
    driver: bridge
volumes:
  prometheus-data:
    driver: local
  vault-data:
    driver: local
  grafana-data:
    driver: local
  pong-dist:
    driver: local
