global:
  scrape_interval: 10s

rule_files:
  - "/etc/prometheus/alertRules.yaml"
  
scrape_configs:

  - job_name: 'prometheus-dev'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'auth-service-dev'
    metrics_path: /metrics
    static_configs:
      - targets: ['auth-service-dev:3001']

  - job_name: 'user-service-dev'
    metrics_path: /metrics
    static_configs:
      - targets: ['user-service-dev:3002']

  - job_name: 'global-chat-dev'
    metrics_path: /metrics
    static_configs:
      - targets: ['global-chat-dev:3003']

  - job_name: 'private-chat-dev'
    metrics_path: /metrics
    static_configs:
      - targets: ['private-chat-dev:8405']

  - job_name: 'pong-game-dev'
    metrics_path: /metrics
    static_configs:
      - targets: ['pong-game-dev:3005']
