services:
  log-generator:
    build:
      context: .
      dockerfile: Dockerfile.generate_logs
    image: log-generator:42
    container_name: log-generator
    networks:
      - elk-net
    # depends_on: #netcat method
    #   - logstash
    # logging: #docker deamon and udp connection using gelf method
    #   driver: gelf
    #   options:
    #     gelf-address: udp://127.0.0.1:12201 # upd so there is no 3 way handshake
    #     tag: log_generator

  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.1
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      # - "5000:5000/tcp"
      # - 12201:12201/udp
      - 5001:5001/tcp
    networks:
      - elk-net
    depends_on:
      - elasticsearch

  fluent-bit:
    image: fluent/fluent-bit:4.1.1
    container_name: fluent-bit
    networks:
      - elk-net
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - /var/lib/docker/containers:/var/log/containers:ro
      - fluent-db:/var/log
    depends_on:
      - logstash
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elk-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kibana
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
    ports:
      - "5601:5601"
    networks:
      - elk-net
    depends_on:
      - elasticsearch

volumes:
  es-data:
    driver: local
    name: es-data
  fluent-db:
    driver: local
    name: fluent-db

networks:
  elk-net:
    driver: bridge
    name: elk-net