global:
  scrape_interval: 10s

scrape_configs:

  - job_name: 'prometheus-dev'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'auth-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['auth-service-dev:3001']

  - job_name: 'user-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['user-service-dev:3002']
