global:
  scrape_interval: 10s

scrape_configs:

  - job_name: 'prometheus-dev'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'backend-dev'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend-dev:3000']
